version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: node:alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: npm run coverage
      - run:
          name: send-coverage-report
          command: cat ./coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
